### ISSUE TITLE
Images not viewed Uncaught TypeError: Cannot set properties of undefined (setting 'lozad') Error in Console

### ISSUE THREAD

**Issue by lukas735** [ApoorvSaxena/lozad.js#295]
I added the library and got this 2 errors in console.
```
Uncaught TypeError: Cannot set properties of undefined (setting 'lozad')
    at lozad.min.js:4:143
    at lozad.min.js:4:148
   lozad is not defined 
       at lozad.js:1
```
    
   This error occure in the ibrary file (lozad.min.js)  My first try was the source of my library. Firstly i got it from https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js now i loaded it with npm ... Same error.
   
   So i asked GPT and he just gave some small adjustments... First my code looked like this:
   ```
const observer = lozad()
   observer.observe();
```
   
   Now it looks like this:
 ```
  function waitForLozad() {
	if (typeof lozad !== 'undefined') {
		// `lozad` is defined, proceed with your code
		const observer = lozad('.lozad', {
		rootMargin: '200px 0px',
		threshold: 0.1
		});
		observer.observe();
	} else {
		// Wait for a short time and then check again
		setTimeout(waitForLozad, 100);
	}
}

waitForLozad(); //Start waiting for lozad.min.js script
```

This just let disappear the lozad is not defined error but not the TypeError i viewed at the top. Does anybody know how this occure ?

**Comment by lukas735** [comment]
I loaded the Script manuelly outside of my normal collecting componets script in the head Area and it worked. Maybe somebody with the same Problem would find this helpful.
